version: '3'

services:
  nginx-stable:
    env_file:
      - .env
    image: nginx:stable
    volumes:
      - ./dockers/config/nginx/conf.d/sites.conf:/etc/nginx/conf.d/sites.conf
      - ./dockers/config/nginx/conf.d/upstream.conf:/etc/nginx/conf.d/upstream.conf
      - ./dockers/config/nginx/conf.d/site_params.template:/etc/nginx/templates/site_params.template
      - ./dockers/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www
    depends_on:
      - php-7.3
      - postgresql-12.4
    ports:
      - 80:80
    networks:
      - app-network
    environment:
      NGINX_HOST: "${APP_URL}"
      NGINX_PORT: "${APP_PORT}"
      NGINX_ROOT: "/var/www/public"
    command:  "nginx -g 'daemon off;'"
  postgresql-12.4:
    env_file:
      - .env
    image: postgres:12.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - app-network
  php-7.3:
    env_file:
      - .env
    build:
      context: ./dockers/compose/php
    volumes:
      - ./dockers/config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    depends_on:
      - postgresql-12.4
    ports:
      - 9000:9000
      - 22:22
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
